### PR TITLE
Template element should be a container.

### PR DESCRIPTION
**Pull request by shapiroronny**
According to : https://www.w3schools.com/tags/tag_template.asp

### CODE REVIEW

**Comment by shapiroronny** [comment]
In HtmlUnit repo it's easily reproducible.

```@Test
    public void template() throws Exception {
        final String html = "<html>\n"
                + "<head>\n"
                + "</head>\n"
                + "<body>\n"
                + "<template>\n"
                + "<div></div\n"
                + "</template>\n"
                + "</body>\n"
                + "</html>";

        try (WebClient webClient = new WebClient(getBrowserVersion(), false, null, -1)) {
            HtmlPage htmlPage = loadPage(webClient, html, null, URL_FIRST);
            System.out.println(htmlPage.asXml());
        }
    }```

The inner div gets removed.

**Comment by rbri** [comment]
Have not seen any effect in changing this. But will add it anyway.

**Comment by shapiroronny** [comment]
Ok sorry, this fix was a bit naive of me, even though it's 'right'.

The issue is caused by HtmlTemplate in HtmlUnit.
The `onAllChildrenAddedToPage` removes the children from the element and stores them in a temp private element named `domDocumentFragment_`.

A suggested fix i'd be happy to make is to override `asXml` and print the children using `domDocumentFragment_`. 
Does it makes sense ? Does omitting children in the asXml method intended ?

**Comment by rbri** [comment]
> A suggested fix i'd be happy to make is to override asXml and print the children using 

Yes please. Any help is welcome.
But please start a new branch in your repo for this

**Pull request closed without merging**
