### PR TITLE
Add feature to allow for parsing of self closing script tags

### PR DESCRIPTION
**Pull request by Seanstoppable**
I discovered that my company was maintaining a fork to handle unclosed script tags.
Since functionality exists to enable handling for unclosed iframes and other unclosed tags, this brings in a similar feature to close that gap.

### CODE REVIEW

**Comment by rbri** [comment]
Thanks @Seanstoppable will have a look....

**Comment by rbri** [comment]
Hi @Seanstoppable,

i'm more in favor to remove features than adding new ones ;-). Can you tell me please a bit about the motivation behind this?

**Comment by Seanstoppable** [comment]
Sure, absoluately understand.

I am currently maintaining a bunch of crawlers. At one point, we apparently decided we wanted to capture self closing script tags in our parsing (despite them being non-compliant). In these cases, we are still attempting to parse the attributes, in particular the script src attribute. We have a fork for essentially these lines, which I am attempting to bring up to date. Rather than maintaining a fork for these lines, I am hoping to contribute back so we can go back to using official published jars. 

Since self-closed iframes are also supported (despite also not being compliant), I was hoping this would bring parity for this tag and a reasonable addition.

**Comment by rbri** [comment]
Ok, sounds reasonable - and having more users is always good for a product ;-)

It will be great, if you can change the way you wrote the tests. Please remove the added junit tests and instead create some test cases like we have for the iframe feature.

Tests are usually done by placing an html file, an optional settings file (to enable some features) and files for the expected results in the correct folder.

You can use this bunch of files as sample
image

And feel free to add as many test cases as you like - if required i will add similar tests to the iframe stuff.

Thanks a lot for bringing this up.

**Comment by Seanstoppable** [comment]
Absolutely. Tests added.
One of them is failing, the frg one. It is saying there is an extra newline being generated (but ONLY for this test), which has left me scratching my head.

**Comment by rbri** [comment]
@Seanstoppable will merge this and have a look

**Comment by rbri** [comment]
@Seanstoppable fixed (see commit) and made a new snapshot build available.

Thanks for your contribution

**Comment by Seanstoppable** [comment]
Awesome, thanks!

**Pull request merged**
