### PR TITLE
Make fields of HTMLWriterFilter from private to protected

### PR DESCRIPTION
**Pull request by slodha-atlassian**

### CODE REVIEW

**Comment by sumollodha** [comment]
https://github.com/HtmlUnit/htmlunit-neko/issues/79#issuecomment-1975981660

**Comment by rbri** [comment]
@sumollodha  is this still needed?

**Comment by sumollodha** [comment]
Nope. We can decline this PR

**Comment by rbri** [comment]
@sumollodha great thanks.

**Pull request closed without merging**
